homeassistant:
  name: !secret home_name
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  unit_system: metric
  temperature_unit: C
  time_zone: America/Sao_Paulo
  currency: BRL
  allowlist_external_dirs:
    - /config
  packages: !include_dir_named include

default_config:
energy:

# Text to speech
tts:
  - platform: google_translate

browser_mod:
  prefix: browser_

map:
  dark_mode: true

lovelace:
  mode: yaml #use ui-lovelace.yaml
  resources: #hacs
    [
      { url: /hacsfiles/apexcharts-card/apexcharts-card.js, type: module },
      { url: /hacsfiles/bar-card/bar-card.js, type: module },
      { url: /hacsfiles/button-card/button-card.js, type: module },
      { url: /hacsfiles/lovelace-hui-element/hui-element.js, type: module },
      { url: /hacsfiles/lovelace-layout-card/layout-card.js, type: module },
      { url: /hacsfiles/lovelace-card-mod/card-mod.js, type: module },
      { url: /hacsfiles/swipe-card/swipe-card.js, type: module },
      { url: /hacsfiles/light-popup-card/light-popup-card.js, type: module },
      { url: /hacsfiles/light-entity-card/light-entity-card.js, type: module },
      {
        url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js,
        type: module,
      },

      { url: "/local/calendar-card.js?v=3.109.1", type: module },
      { url: "/local/custom_icons.js?v=28082021", type: module },
      { url: "/local/marked.min.js?v=4.0.12", type: module },
      { url: "/local/vanilla-tilt.min.js?v=1.7.2", type: module },
      { url: /local/font.css, type: css },
    ]

# Custom components
nicehash:
  organization_id: !secret nice-hash-organization_id
  api_key: !secret nice-hash-api_key
  api_secret: !secret nice-hash-api_secret
  currency: USD
  balances: true
  rigs: true
  devices: true
  payouts: true
