homeassistant:
  name: !secret home_name
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  internal_url: !secret internal_url
  external_url: !secret external_url
  unit_system: metric
  temperature_unit: C
  time_zone: !secret time_zone
  currency: BRL
  allowlist_external_dirs: [/config/]
  packages: !include_dir_named include

default_config:
config:
energy:
mobile_app:
template: !include_dir_merge_list templates
browser_mod:
  prefix: browser_

recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 5
  commit_interval: 30

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

lovelace:
  mode: yaml
  resources:
    [
      { url: /hacsfiles/bar-card/bar-card.js, type: module },
      { url: /hacsfiles/button-card/button-card.js, type: module },
      { url: /hacsfiles/lovelace-hui-element/hui-element.js, type: module },
      { url: /hacsfiles/lovelace-layout-card/layout-card.js, type: module },
      { url: /hacsfiles/lovelace-card-mod/card-mod.js, type: module },
      { url: /hacsfiles/light-popup-card/light-popup-card.js, type: module },
      { url: /hacsfiles/light-entity-card/light-entity-card.js, type: module },
      { url: /hacsfiles/sidebar-card/sidebar-card.js, type: module },
      {
        url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js,
        type: module,
      },
      { url: "/local/custom_icons.js?v=28082021", type: module },
      { url: "/local/marked.min.js?v=4.0.12", type: module },
      { url: "/local/vanilla-tilt.min.js?v=1.7.2", type: module },
      { url: /local/font.css, type: css },
    ]
