automation:
  # Presence detection

  - alias: Turn all leds off when home leave
    id: "18978458711"
    trigger:
      - entity_id: person.jonathan_ferraz
        platform: state
        from: home
        to: not_home
    condition: []
    action:
      - entity_id: light.ambilight
        service: light.turn_off
      - entity_id: light.mesa
        service: light.turn_off
      - service: switch.turn_off
        entity_id: switch.hyperion_controller
      - service: switch.turn_off
        entity_id: switch.monitor_power
      - data: {}
        service: script.pc_gamer_lock
      - service: notify.mobile_app_iphone
        data:
          title: >
            Detecção de presença
          message: "Desligando as leds do setup"

  - alias: Turn all leds on when home enter
    id: "18978458712"
    trigger:
      - entity_id: person.jonathan_ferraz
        platform: state
        from: not_home
        to: home
    condition: []
    action:
      - entity_id: light.ambilight
        service: light.turn_on
      - entity_id: light.mesa
        service: light.turn_on
      - service: switch.turn_on
        entity_id: switch.hyperion_controller
      - service: switch.turn_on
        entity_id: switch.monitor_power
      - service: notify.mobile_app_iphone
        data:
          title: >
            Detecção de presença
          message: "Ligando as leds do setup"

  - alias: person_home
    id: "18978458714"
    mode: parallel
    trigger:
      platform: state
      entity_id:
        - person.jonathan_ferraz
        - person.matheus_ferraz
      from:
        - home
        - not_home
      to:
        - home
        - not_home
    action:
      service: mqtt.publish
      data:
        topic_template: >
          homeassistant/persistence/{{ trigger.to_state.attributes.id | lower }}
        payload_template: >
          {{ now() }}
        retain: true

  # LED Routine

  - alias: Setup led morning
    id: "18978458715"
    trigger:
      - platform: time
        at: "09:25:00"
    condition:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
      - condition: template
        value_template: >
          {{states('device_tracker.iphone_de_matt') != 'home'}}
    action:
      - service: light.turn_on
        data:
          entity_id: light.ambilight
      - service: light.turn_on
        data:
          entity_id: light.mesa
      - service: select.select_option
        target:
          entity_id: select.mesa_preset
        data:
          option: Morning
      - service: select.select_option
        target:
          entity_id: select.ambilight_preset
        data:
          option: Morning

  - alias: Setup led effects
    id: "18978458716"
    trigger:
      platform: time
      at: "10:30:00"
    condition:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
      - condition: state
        entity_id: light.mesa
        state: "on"
      - condition: state
        entity_id: light.ambilight
        state: "on"
      - condition: template
        value_template: >
          {{states('device_tracker.iphone_de_matt') != 'home'}}
    action:
      - service: select.select_option
        target:
          entity_id: select.mesa_preset
        data:
          option: Chroma
      - service: switch.turn_on
        entity_id: switch.hyperion_controller

  - alias: Turn on script on workdays
    id: "18978458718"
    trigger:
      platform: time
      at: "09:25:00"
    condition:
      condition: state
      entity_id: binary_sensor.workday_sensor
      state: "on"
    action:
      - service: switch.turn_on
        entity_id: switch.monitor_power
      - delay: "00:00:05"
      - data: {}
        service: script.pc_gamer_start_work

  # Other

  - alias: Clear log filesize
    id: "18978458713"
    trigger:
      platform: numeric_state
      entity_id: sensor.home_assistant_log_size
      above: 50
    action:
      service: shell_command.ha_purge_logs

  - alias: Rig miner alert
    id: "18978458717"
    trigger:
      - platform: state
        entity_id: sensor.setup_speed
        to: "0"
    condition:
      - condition: state
        entity_id: sensor.setup_status
        state: Mining
      - condition: time
        after: "09:00:00"
        before: "00:00:00"
    action:
      - service: notify.mobile_app_iphone
        data:
          title: RIG Status
          message: A RIG não está minerando!
          data:
            push:
              sound:
                name: default
                critical: 1
                volume: 1
      - condition: state
        entity_id: person.jonathan_ferraz
        state: home
      - service: notify.alexa_media_echo_dot_de_jonathan
        data:
          message: Não está minerando
          data:
            type: tts

  # Battery Alert

  - alias: iPhone battery low
    id: "18978458719"
    trigger:
      - platform: numeric_state
        entity_id: sensor.iphone_battery_level
        below: 21
    condition:
      - condition: state
        entity_id: sensor.iphone_battery_state
        state: "Not Charging"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: device_tracker.iphone
                state: "home"
            sequence:
              - service: notify.alexa_media_echo_dot_de_jonathan
                data:
                  message: Colocar iPhone para carregar
                  data:
                    type: tts
              - service: notify.mobile_app_iphone
                data:
                  title: Aviso de bateria
                  message: A bateria do seu iPhone precisa ser carregada
                  data:
                    message: carregue o iPhone
          - conditions:
              - condition: state
                entity_id: device_tracker.iphone
                state: "not_home"
            sequence:
              - service: notify.mobile_app_iphone
                data:
                  title: Aviso de bateria
                  message: A bateria do seu iPhone precisa ser carregada
                  data:
                    message: carregue o iPhone

  - alias: iPhone battery full
    id: "189784587110"
    trigger:
      - platform: numeric_state
        entity_id: sensor.iphone_battery_level
        above: 99
    condition:
      - condition: state
        entity_id: sensor.iphone_battery_state
        state: "Full"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: device_tracker.iphone
                state: "home"
            sequence:
              - service: notify.mobile_app_iphone
                data:
                  title: Aviso de bateria
                  message: A bateria do seu iPhone está carregada
                  data:
                    message: retire do carregador
              - service: notify.alexa_media_echo_dot_de_jonathan
                data:
                  message: O iPhone está carregado
                  data:
                    type: tts
          - conditions:
              - condition: state
                entity_id: device_tracker.iphone
                state: "not_home"
            sequence:
              - service: notify.mobile_app_iphone
                data:
                  title: Aviso de bateria
                  message: A bateria do seu iPhone está carregada
                  data:
                    message: retire do carregador

  - alias: Restart IOTLink
    id: "189784587111"
    trigger:
      - platform: time_pattern
        minutes: "/10"
    condition:
      - condition: state
        entity_id: sensor.pc_gamer_ssd_usado_c
        state: "unknown"
      - condition: state
        entity_id: device_tracker.iphone
        state: "home"
    action:
      - service: notify.mobile_app_iphone
        data:
          title: PC Status
          message: IOTLink irá reiniciar em 10seg
          data:
            message: IOTLink irá reiniciar em 10seg
      - delay: "00:00:10"
      - data: {}
        service: script.pc_gamer_restart_iotlink
