automation:
  - alias: clear_log_filesize
    id: "3331821824310"
    trigger:
      platform: numeric_state
      entity_id: sensor.home_assistant_log_size
      above: 50
    action:
      service: shell_command.ha_purge_logs

  - alias: ios_notify_hass_update
    id: "7958228563778"
    variables:
      latest: >
        {{ states(trigger.entity_id) }}
      installed: >
        {{ states('sensor.hass_version_installed') }}
    trigger:
      platform: state
      entity_id: sensor.hass_version_latest
    condition: >
      {{ installed != latest if '.' in installed and '.' in latest else false }}
    action:
      - service: homeassistant.update_entity
        target:
          entity_id:
            - sensor.hass_release_notes
            - sensor.hass_release_notes_rc
      - delay:
          minutes: 30
      - service: notify.mobile_app_iphone
        data:
          title: >
            {{ latest }} acessível {{ '\U0001F389' }}
          message: Segure para atualizar
          data:
            url: https://www.home-assistant.io/latest-release-notes/
            actions:
              - action: START_WATCHTOWER
                title: Atualizar

  - alias: person_home
    id: "8423590985012"
    mode: parallel
    trigger:
      platform: state
      entity_id:
        - person.jonathan_ferraz
      from:
        - home
        - not_home
      to:
        - home
        - not_home
    action:
      service: mqtt.publish
      data:
        topic_template: >
          homeassistant/persistence/{{ trigger.to_state.name | lower }}
        payload_template: >
          {{ now() }}
        retain: true
