binary_sensor:
  - platform: mqtt
    name: "My Computer - Connected"
    state_topic: "iotlink/workgroup/setup/lwt"
    value_template: "{{ value }}"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: "connectivity"
    qos: 1

  - platform: workday
    country: BR
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]
    add_holidays:
      - "2022-01-01"
      - "2022-04-21"
      - "2022-05-01"
      - "2022-06-11"
      - "2022-09-07"
      - "2022-10-12"
      - "2022-11-02"
      - "2022-11-15"
      - "2022-12-25"
