binary_sensor:
  - platform: mqtt
    name: "My Computer - Connected"
    state_topic: "iotlink/workgroup/setup/lwt"
    value_template: "{{ value }}"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: "connectivity"
    qos: 1

  - platform: workday
    country: BR
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]
    add_holidays:
      - "2022-01-01"
      - "2022-04-21"
      - "2022-05-01"
      - "2022-06-11"
      - "2022-09-07"
      - "2022-10-12"
      - "2022-11-02"
      - "2022-11-15"
      - "2022-12-25"
      # Férias
      - "2022-08-22"
      - "2022-08-23"
      - "2022-08-24"
      - "2022-08-25"
      - "2022-08-26"
      - "2022-08-27"
      - "2022-08-28"
      - "2022-08-29"
      - "2022-08-30"
      - "2022-08-31"
      - "2022-09-01"
      - "2022-09-02"
      - "2022-09-03"
      - "2022-09-04"
      - "2022-09-05"
      - "2022-09-06"
      - "2022-09-07"
      - "2022-09-08"
      - "2022-09-09"
      - "2022-09-10"
