homeassistant:
  customize_domain:
    automation:
      initial_state: true

  customize:
    #person
    person.jonathan_ferraz:
      entity_picture: /local/jonathan.jpg
    device_tracker.iphone_de_jonathan:
      entity_picture: /local/device_tracker.svg
    person.matheus_ferraz:
      entity_picture: /local/matheus.jpg
    device_tracker.iphone_de_matt:
      entity_picture: /local/device_tracker.svg

    #Sensor
    sensor.home_assistant_v2_db:
      friendly_name: Database
      icon: mdi:database

    sensor.uptime:
      friendly_name: Uptime
      icon: mdi:update
      device_class: timestamp
