homeassistant:
  customize_domain:
    automation:
      initial_state: true

  customize:
    #person
    person.jonathan_ferraz:
      entity_picture: /local/jonathan.jpg
    device_tracker.iphone:
      entity_picture: /local/device_tracker.svg
    person.matheus_ferraz:
      entity_picture: /local/matheus.jpg

    #media_player
    media_player.spotify:
      friendly_name: Spotify

    #Sensor
    sensor.monitors_volume:
      icon: mdi:volume-high

    sensor.home_assistant_v2_db:
      friendly_name: Databas
      icon: mdi:database

    sensor.home_assistant_log:
      friendly_name: Loggfil
      icon: mdi:file-document

    sensor.imac_uptime:
      friendly_name: Senaste omstart
      icon: mdi:update
      device_class: timestamp

    sensor.uptime:
      friendly_name: Senast omstart
      icon: mdi:update
      device_class: timestamp
