sensor:
  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db
      - /config/home-assistant.log

  - platform: time_date
    display_options:
      - time
      - date

  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot

  - platform: template
    sensors:
      # Mining tracker
      btc_price:
        friendly_name: "Bitcoin Price"
        unit_of_measurement: "BRL"
        value_template: "{{ ((states.sensor.coinmarketcap_curl.attributes.data.BTC.quote.BRL.price) | float) | round(2) }}"

      rtx3060_speed_formatted:
        friendly_name: "RTX 3060 Speed"
        unit_of_measurement: "MH/s"
        value_template: "{{ states('sensor.geforce_rtx_3060_speed') | float | round(2)}}"

      gtx1660_speed_formatted:
        friendly_name: "GTX 1660 Speed"
        unit_of_measurement: "MH/s"
        value_template: "{{ states('sensor.geforce_gtx_1660_speed') | float | round(2)}}"

      average_btc:
        friendly_name: "Average BTC"
        value_template: "{{ (states('sensor.mean_btc_price') | float) | round(0) }}"

      min_btc:
        friendly_name: "Min BTC"
        value_template: "{{ (states('sensor.mean_btc_price') | float * 0.973) | round(0) }}"

      mid_btc:
        friendly_name: "Mid BTC"
        value_template: "{{ (states('sensor.mean_btc_price') | float * 0.987) | round(0) }}"

      # Weather
      weather_precipitation:
        friendly_name: "Chance de chuva"
        value_template: "{{ states('sensor.home_precipitation') | float }}"

      weather_temperature:
        friendly_name: "Temperatura"
        entity_id: weather.home
        value_template: "{{ state_attr('weather.home', 'temperature') }}"

      weather_humidity:
        friendly_name: "Humidade"
        entity_id: weather.home
        value_template: "{{ state_attr('weather.home', 'humidity') }}"
        unit_of_measurement: "%"

      # Hass
      hass_version_installed:
        friendly_name: "Home Assistant Core: Installed"
        entity_id: update.home_assistant_core_update
        value_template: "{{ state_attr('update.home_assistant_core_update', 'installed_version') }}"

      hass_version_latest:
        friendly_name: "Home Assistant Core: Latest"
        entity_id: update.home_assistant_core_update
        value_template: "{{ state_attr('update.home_assistant_core_update', 'latest_version') }}"

  - platform: command_line
    name: hacs_installed
    command: |-
      python3 << EOF
      import os, json
      installed = {"repositories": []}
      path = "/config/.storage/hacs/"
      for file in os.listdir(path):
          name, ext = os.path.splitext(file)
          if ext == ".hacs":
              hacs_file = path + file
              with open(hacs_file, "r") as file:
                  dict = json.load(file)
                  name = dict["data"]["full_name"]
                  installed["repositories"] += [name]
                  file.close()
      print(json.dumps(installed))
      EOF
    value_template: >
      {{ value_json.repositories | count }}
    json_attributes:
      - repositories
    scan_interval: 86400

  - platform: average
    name: "Mean BTC price"
    duration:
      hours: 12
      minutes: 00
    entities:
      - sensor.btc_price

  # Coinmarketcap
  - platform: command_line
    name: coinmarketcap_curl
    command: !secret coinmarketcap-url
    value_template: "{{ value_json.value }}"
    scan_interval: 300 #5 mins refresh (this rate will use 288 credits per day out of the allocated 333 credits)
    json_attributes:
      - data

  - platform: integration
    source: sensor.tomada_pc_gamer_power
    name: PC Gamer - Consumo
    unit_prefix: k
    round: 2

  - platform: powercalc
    create_group: All setup leds kWh
    name: LED Setup kWh
    entities:
      - entity_id: light.ambilight
      - entity_id: light.mesa
    wled:
      voltage: 5

  # IOTLink

  - platform: mqtt
    name: "PC Gamer - CPU Usada"
    state_topic: "iotlink/workgroup/setup/windows-monitor/stats/cpu/usage"
    unit_of_measurement: "%"
    icon: mdi:speedometer
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/setup/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "PC Gamer - RAM Usada"
    state_topic: "iotlink/workgroup/setup/windows-monitor/stats/memory/usage"
    unit_of_measurement: "%"
    icon: mdi:memory
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/setup/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "PC Gamer - SSD Usado (C)"
    state_topic: "iotlink/workgroup/setup/windows-monitor/stats/hard-drive/c/drive-usage"
    unit_of_measurement: "%"
    icon: mdi:chart-donut
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/setup/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "PC Gamer - Up Time"
    state_topic: "iotlink/workgroup/setup/windows-monitor/stats/system/uptime"
    unit_of_measurement: "seconds"
    icon: mdi:timer
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/setup/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1
