sensor:
  - platform: time_date
    display_options:
      - time
      - date

  - platform: template
    sensors:
      precipitation:
        friendly_name: "Chance de chuva"
        value_template: "{{ states('sensor.home_precipitation') | float }}"

  - platform: template
    sensors:
      # Mining tracker
      btc_price:
        friendly_name: "Bitcoin Price"
        unit_of_measurement: "BRL"
        value_template: "{{ ((states.sensor.coinmarketcap_curl.attributes.data.BTC.quote.BRL.price) | float) | round(2) }}"
      rtx3060_speed_formatted:
        friendly_name: "RTX 3060 Speed"
        unit_of_measurement: "MH/s"
        value_template: "{{ states('sensor.geforce_rtx_3060_speed') | float | round(2)}}"
      gtx1660_speed_formatted:
        friendly_name: "GTX 1660 Speed"
        unit_of_measurement: "MH/s"
        value_template: "{{ states('sensor.geforce_gtx_1660_speed') | float | round(2)}}"

  # Coinmarketcap
  - platform: command_line
    name: coinmarketcap_curl
    command: !secret coinmarketcap-url
    value_template: "{{ value_json.value }}"
    scan_interval: 300 #5 mins refresh (this rate will use 288 credits per day out of the allocated 333 credits)
    json_attributes:
      - data

  - platform: integration
    source: sensor.tomada_pc_gamer_power
    name: PC Mineração - Consumo
    unit_prefix: k
    round: 2
