sensor:
  - platform: time_date
    display_options:
      - time
      - date

  - platform: command_line
    name: hacs_installed
    command: |-
      python3 << EOF
      import os, json
      installed = {"repositories": []}
      path = "/config/.storage/hacs/"
      for file in os.listdir(path):
          name, ext = os.path.splitext(file)
          if ext == ".hacs":
              hacs_file = path + file
              with open(hacs_file, "r") as file:
                  dict = json.load(file)
                  name = dict["data"]["full_name"]
                  installed["repositories"] += [name]
                  file.close()
      print(json.dumps(installed))
      EOF
    value_template: >
      {{ value_json.repositories | count }}
    json_attributes:
      - repositories
    scan_interval: 86400

  - platform: template
    sensors:
      # Mining tracker
      btc_price:
        friendly_name: "Bitcoin Price"
        unit_of_measurement: "BRL"
        value_template: "{{ ((states.sensor.coinmarketcap_curl.attributes.data.BTC.quote.BRL.price) | float) | round(2) }}"
      rtx3060_speed_formatted:
        friendly_name: "RTX 3060 Speed"
        unit_of_measurement: "MH/s"
        value_template: "{{ states('sensor.geforce_rtx_3060_speed') | float | round(2)}}"
      gtx1660_speed_formatted:
        friendly_name: "GTX 1660 Speed"
        unit_of_measurement: "MH/s"
        value_template: "{{ states('sensor.geforce_gtx_1660_speed') | float | round(2)}}"

  # Coinmarketcap
  - platform: command_line
    name: coinmarketcap_curl
    command: !secret coinmarketcap-url
    value_template: "{{ value_json.value }}"
    scan_interval: 300 #5 mins refresh (this rate will use 288 credits per day out of the allocated 333 credits)
    json_attributes:
      - data

  - platform: integration
    source: sensor.tomada_pc_gamer_power
    name: PC Mineração - Consumo
    unit_prefix: k
    round: 2
